### ISSUE TITLE
Change SVN URL format to short/pretty form

### ISSUE THREAD

**Issue by koobs** [dlangille/freshports#1]
!! ISSUE ONE, YEH BABY !!

Currently, freshports SVN urls are in the form:

http://svnweb.freebsd.org/ports?view=revision&revision=<revision-id>

An alternative (shorter) form is supported, as follows:

https://svnweb.freebsd.org/changeset/ports/390304

These correctly redirect and expand to the correct place, but are much prettier when copying/pasting (especially into bugzilla, and other third party systems)

It might also help Google juice and URL crawl-ability in some cases

PS: Congratulations on the repo! I look forward to an export of the freshports.org code soon ;)

**Comment by dlangille** [comment]
Committed, but not in production.

**Comment by dlangille** [comment]
This is now in production (some time ago).
