### ISSUE TITLE
E2guardian old version

### ISSUE THREAD

**Issue by BillRizer** [dlangille/freshports#33]
Hi, I'm trying to update e2guardian for v5.1 but the port is with the latest version as 3.5.1.

how should I do ?

Thank  😃 

E2guardian repo:
https://github.com/e2guardian/e2guardian/releases

**Comment by dlangille** [comment]
FreshPorts only reports on what is in the ports tree.  We don't update the ports themselves.

You need to talk to the www/e2guardian maintainer. https://www.freshports.org/www/e2guardian/ has a link for that.

Does this help?

**Comment by BillRizer** [comment]
Thanks 😄
